Document: lxqt-config
Title: Debian lxqt-config Manual
Author: <insert document author here>
Abstract: This manual describes what lxqt-config is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/lxqt-config/lxqt-config.sgml.gz

Format: postscript
Files: /usr/share/doc/lxqt-config/lxqt-config.ps.gz

Format: text
Files: /usr/share/doc/lxqt-config/lxqt-config.text.gz

Format: HTML
Index: /usr/share/doc/lxqt-config/html/index.html
Files: /usr/share/doc/lxqt-config/html/*.html
