Document: lxqt-globalkeys
Title: Debian lxqt-globalkeys Manual
Author: <insert document author here>
Abstract: This manual describes what lxqt-globalkeys is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/lxqt-globalkeys/lxqt-globalkeys.sgml.gz

Format: postscript
Files: /usr/share/doc/lxqt-globalkeys/lxqt-globalkeys.ps.gz

Format: text
Files: /usr/share/doc/lxqt-globalkeys/lxqt-globalkeys.text.gz

Format: HTML
Index: /usr/share/doc/lxqt-globalkeys/html/index.html
Files: /usr/share/doc/lxqt-globalkeys/html/*.html
