Document: lxqt-session
Title: Debian lxqt-session Manual
Author: <insert document author here>
Abstract: This manual describes what lxqt-session is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/lxqt-session/lxqt-session.sgml.gz

Format: postscript
Files: /usr/share/doc/lxqt-session/lxqt-session.ps.gz

Format: text
Files: /usr/share/doc/lxqt-session/lxqt-session.text.gz

Format: HTML
Index: /usr/share/doc/lxqt-session/html/index.html
Files: /usr/share/doc/lxqt-session/html/*.html
