Document: lxqt-common
Title: Debian lxqt-common Manual
Author: <insert document author here>
Abstract: This manual describes what lxqt-common is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/lxqt-common/lxqt-common.sgml.gz

Format: postscript
Files: /usr/share/doc/lxqt-common/lxqt-common.ps.gz

Format: text
Files: /usr/share/doc/lxqt-common/lxqt-common.text.gz

Format: HTML
Index: /usr/share/doc/lxqt-common/html/index.html
Files: /usr/share/doc/lxqt-common/html/*.html
