Document: liblxqt
Title: Debian liblxqt Manual
Author: <insert document author here>
Abstract: This manual describes what liblxqt is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/liblxqt/liblxqt.sgml.gz

Format: postscript
Files: /usr/share/doc/liblxqt/liblxqt.ps.gz

Format: text
Files: /usr/share/doc/liblxqt/liblxqt.text.gz

Format: HTML
Index: /usr/share/doc/liblxqt/html/index.html
Files: /usr/share/doc/liblxqt/html/*.html
