Document: lxqt-about
Title: Debian lxqt-about Manual
Author: <insert document author here>
Abstract: This manual describes what lxqt-about is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/lxqt-about/lxqt-about.sgml.gz

Format: postscript
Files: /usr/share/doc/lxqt-about/lxqt-about.ps.gz

Format: text
Files: /usr/share/doc/lxqt-about/lxqt-about.text.gz

Format: HTML
Index: /usr/share/doc/lxqt-about/html/index.html
Files: /usr/share/doc/lxqt-about/html/*.html
