Document: lxqt-powermanagement
Title: Debian lxqt-powermanagement Manual
Author: <insert document author here>
Abstract: This manual describes what lxqt-powermanagement is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/lxqt-powermanagement/lxqt-powermanagement.sgml.gz

Format: postscript
Files: /usr/share/doc/lxqt-powermanagement/lxqt-powermanagement.ps.gz

Format: text
Files: /usr/share/doc/lxqt-powermanagement/lxqt-powermanagement.text.gz

Format: HTML
Index: /usr/share/doc/lxqt-powermanagement/html/index.html
Files: /usr/share/doc/lxqt-powermanagement/html/*.html
