Document: lxqt-lightdm-greeter
Title: Debian lxqt-lightdm-greeter Manual
Author: <insert document author here>
Abstract: This manual describes what lxqt-lightdm-greeter is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/lxqt-lightdm-greeter/lxqt-lightdm-greeter.sgml.gz

Format: postscript
Files: /usr/share/doc/lxqt-lightdm-greeter/lxqt-lightdm-greeter.ps.gz

Format: text
Files: /usr/share/doc/lxqt-lightdm-greeter/lxqt-lightdm-greeter.text.gz

Format: HTML
Index: /usr/share/doc/lxqt-lightdm-greeter/html/index.html
Files: /usr/share/doc/lxqt-lightdm-greeter/html/*.html
