Document: lxqt-policykit
Title: Debian lxqt-policykit Manual
Author: <insert document author here>
Abstract: This manual describes what lxqt-policykit is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/lxqt-policykit/lxqt-policykit.sgml.gz

Format: postscript
Files: /usr/share/doc/lxqt-policykit/lxqt-policykit.ps.gz

Format: text
Files: /usr/share/doc/lxqt-policykit/lxqt-policykit.text.gz

Format: HTML
Index: /usr/share/doc/lxqt-policykit/html/index.html
Files: /usr/share/doc/lxqt-policykit/html/*.html
