Document: lxqt-notificationd
Title: Debian lxqt-notificationd Manual
Author: <insert document author here>
Abstract: This manual describes what lxqt-notificationd is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/lxqt-notificationd/lxqt-notificationd.sgml.gz

Format: postscript
Files: /usr/share/doc/lxqt-notificationd/lxqt-notificationd.ps.gz

Format: text
Files: /usr/share/doc/lxqt-notificationd/lxqt-notificationd.text.gz

Format: HTML
Index: /usr/share/doc/lxqt-notificationd/html/index.html
Files: /usr/share/doc/lxqt-notificationd/html/*.html
