Document: libqtxdg
Title: Debian libqtxdg Manual
Author: <insert document author here>
Abstract: This manual describes what libqtxdg is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libqtxdg/libqtxdg.sgml.gz

Format: postscript
Files: /usr/share/doc/libqtxdg/libqtxdg.ps.gz

Format: text
Files: /usr/share/doc/libqtxdg/libqtxdg.text.gz

Format: HTML
Index: /usr/share/doc/libqtxdg/html/index.html
Files: /usr/share/doc/libqtxdg/html/*.html
