Document: lxqt-config-randr
Title: Debian lxqt-config-randr Manual
Author: <insert document author here>
Abstract: This manual describes what lxqt-config-randr is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/lxqt-config-randr/lxqt-config-randr.sgml.gz

Format: postscript
Files: /usr/share/doc/lxqt-config-randr/lxqt-config-randr.ps.gz

Format: text
Files: /usr/share/doc/lxqt-config-randr/lxqt-config-randr.text.gz

Format: HTML
Index: /usr/share/doc/lxqt-config-randr/html/index.html
Files: /usr/share/doc/lxqt-config-randr/html/*.html
