Document: liblxqt-mount
Title: Debian liblxqt-mount Manual
Author: <insert document author here>
Abstract: This manual describes what liblxqt-mount is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/liblxqt-mount/liblxqt-mount.sgml.gz

Format: postscript
Files: /usr/share/doc/liblxqt-mount/liblxqt-mount.ps.gz

Format: text
Files: /usr/share/doc/liblxqt-mount/liblxqt-mount.text.gz

Format: HTML
Index: /usr/share/doc/liblxqt-mount/html/index.html
Files: /usr/share/doc/liblxqt-mount/html/*.html
