Document: lxqt-panel
Title: Debian lxqt-panel Manual
Author: <insert document author here>
Abstract: This manual describes what lxqt-panel is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/lxqt-panel/lxqt-panel.sgml.gz

Format: postscript
Files: /usr/share/doc/lxqt-panel/lxqt-panel.ps.gz

Format: text
Files: /usr/share/doc/lxqt-panel/lxqt-panel.text.gz

Format: HTML
Index: /usr/share/doc/lxqt-panel/html/index.html
Files: /usr/share/doc/lxqt-panel/html/*.html
