Document: lxqt-openssh-askpass
Title: Debian lxqt-openssh-askpass Manual
Author: <insert document author here>
Abstract: This manual describes what lxqt-openssh-askpass is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/lxqt-openssh-askpass/lxqt-openssh-askpass.sgml.gz

Format: postscript
Files: /usr/share/doc/lxqt-openssh-askpass/lxqt-openssh-askpass.ps.gz

Format: text
Files: /usr/share/doc/lxqt-openssh-askpass/lxqt-openssh-askpass.text.gz

Format: HTML
Index: /usr/share/doc/lxqt-openssh-askpass/html/index.html
Files: /usr/share/doc/lxqt-openssh-askpass/html/*.html
