Document: lxqt-runner
Title: Debian lxqt-runner Manual
Author: <insert document author here>
Abstract: This manual describes what lxqt-runner is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/lxqt-runner/lxqt-runner.sgml.gz

Format: postscript
Files: /usr/share/doc/lxqt-runner/lxqt-runner.ps.gz

Format: text
Files: /usr/share/doc/lxqt-runner/lxqt-runner.text.gz

Format: HTML
Index: /usr/share/doc/lxqt-runner/html/index.html
Files: /usr/share/doc/lxqt-runner/html/*.html
