Document: pcmanfm-qt
Title: Debian pcmanfm-qt Manual
Author: <insert document author here>
Abstract: This manual describes what pcmanfm-qt is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pcmanfm-qt/pcmanfm-qt.sgml.gz

Format: postscript
Files: /usr/share/doc/pcmanfm-qt/pcmanfm-qt.ps.gz

Format: text
Files: /usr/share/doc/pcmanfm-qt/pcmanfm-qt.text.gz

Format: HTML
Index: /usr/share/doc/pcmanfm-qt/html/index.html
Files: /usr/share/doc/pcmanfm-qt/html/*.html
