Document: compton-conf
Title: Debian compton-conf Manual
Author: <insert document author here>
Abstract: This manual describes what compton-conf is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/compton-conf/compton-conf.sgml.gz

Format: postscript
Files: /usr/share/doc/compton-conf/compton-conf.ps.gz

Format: text
Files: /usr/share/doc/compton-conf/compton-conf.text.gz

Format: HTML
Index: /usr/share/doc/compton-conf/html/index.html
Files: /usr/share/doc/compton-conf/html/*.html
