Document: lxqt-qtplugin
Title: Debian lxqt-qtplugin Manual
Author: <insert document author here>
Abstract: This manual describes what lxqt-qtplugin is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/lxqt-qtplugin/lxqt-qtplugin.sgml.gz

Format: postscript
Files: /usr/share/doc/lxqt-qtplugin/lxqt-qtplugin.ps.gz

Format: text
Files: /usr/share/doc/lxqt-qtplugin/lxqt-qtplugin.text.gz

Format: HTML
Index: /usr/share/doc/lxqt-qtplugin/html/index.html
Files: /usr/share/doc/lxqt-qtplugin/html/*.html
