Document: libsysstat
Title: Debian libsysstat Manual
Author: <insert document author here>
Abstract: This manual describes what libsysstat is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libsysstat/libsysstat.sgml.gz

Format: postscript
Files: /usr/share/doc/libsysstat/libsysstat.ps.gz

Format: text
Files: /usr/share/doc/libsysstat/libsysstat.text.gz

Format: HTML
Index: /usr/share/doc/libsysstat/html/index.html
Files: /usr/share/doc/libsysstat/html/*.html
